// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-my-card.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated" }],
    isError: true
  };
}

// src/lib/mcp/tools/get-my-card.ts
var get_my_card_default = defineTool({
  name: "get_my_card",
  title: "Get my Recovery Card",
  description: "Fetch the signed-in participant's Recovery Card: card level, days engaged, program, and profile summary.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data, error } = await sb.from("participant_profiles").select("id, display_name, card_level, days_engaged, program_id, created_at, programs(name, type)").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No participant profile found for this user." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { card: data }
    };
  }
});

// src/lib/mcp/tools/list-my-milestones.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_my_milestones_default = defineTool2({
  name: "list_my_milestones",
  title: "List my milestones",
  description: "List all milestones for the signed-in participant with their status and unlock dates.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("participant_profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "No participant profile." }], isError: true };
    const { data, error } = await sb.from("participant_milestones").select("id, status, unlocked_at, milestone_definitions(name, description, category, points)").eq("participant_id", profile.id);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { milestones: data }
    };
  }
});

// src/lib/mcp/tools/list-my-checkins.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var list_my_checkins_default = defineTool3({
  name: "list_my_checkins",
  title: "List my weekly check-ins",
  description: "List the signed-in participant's recent weekly check-ins, most recent first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Max number of check-ins to return")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("participant_profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "No participant profile." }], isError: true };
    const { data, error } = await sb.from("weekly_checkins").select("*").eq("participant_id", profile.id).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { checkins: data }
    };
  }
});

// src/lib/mcp/tools/log-self-care-check.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var log_self_care_check_default = defineTool4({
  name: "log_self_care_check",
  title: "Log a self-care check",
  description: "Record a self-care check-in (mood, energy, stress on a 1-5 scale) for the signed-in user. Auto-flags if stress >= 4 or mood <= 2.",
  inputSchema: {
    mood: z2.number().int().min(1).max(5).describe("Mood 1 (low) to 5 (great)"),
    energy: z2.number().int().min(1).max(5).describe("Energy 1 (drained) to 5 (energized)"),
    stress: z2.number().int().min(1).max(5).describe("Stress 1 (calm) to 5 (overwhelmed)"),
    notes: z2.string().max(2e3).optional().describe("Optional free-text notes")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ mood, energy, stress, notes }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const is_flagged = stress >= 4 || mood <= 2;
    const { data, error } = await sb.from("self_care_checks").insert({ user_id: ctx.getUserId(), mood, energy, stress, notes: notes ?? null, is_flagged }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged self-care check${is_flagged ? " (flagged for follow-up)" : ""}.` }],
      structuredContent: { check: data, is_flagged }
    };
  }
});

// src/lib/mcp/tools/get-my-recovery-plan.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_my_recovery_plan_default = defineTool5({
  name: "get_my_recovery_plan",
  title: "Get my recovery plan",
  description: "Fetch the signed-in participant's current recovery plan with its phases and action steps.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const sb = supabaseForUser(ctx);
    const { data: profile } = await sb.from("participant_profiles").select("id").eq("user_id", ctx.getUserId()).maybeSingle();
    if (!profile) return { content: [{ type: "text", text: "No participant profile." }], isError: true };
    const { data, error } = await sb.from("recovery_plans").select("*, plan_phases(*, plan_action_steps(*))").eq("participant_id", profile.id).order("created_at", { ascending: false }).limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "No recovery plan yet. Complete an assessment first." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { plan: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "axligiieeuzmahkhmxwy";
var mcp_default = defineMcp({
  name: "recovery-passport-mcp",
  title: "Recovery Passport",
  version: "0.1.0",
  instructions: "Tools for a Recovery Passport participant. Every tool acts as the signed-in user via Supabase RLS. Use `get_my_card` for the participant's card, `list_my_milestones` for milestone progress, `list_my_checkins` for recent weekly check-ins, `get_my_recovery_plan` for the active plan, and `log_self_care_check` to record a mood/energy/stress check-in.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_card_default, list_my_milestones_default, list_my_checkins_default, log_self_care_check_default, get_my_recovery_plan_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
